const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.Flash,
		C3.Plugins.Keyboard,
		C3.Plugins.Tilemap,
		C3.Behaviors.Sin,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.OnMove,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.Compare,
		C3.Behaviors.Sin.Exps.CyclePosition,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.scrollx,
		C3.Plugins.System.Exps.scrolly,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Flash.Cnds.IsFlashing,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Mouse.Cnds.OnObjectClicked
	];
};
self.C3_JsPropNameTable = [
	{Sólido: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{PlanoDeFundoEmBlocos3: 0},
	{Plataforma: 0},
	{ScrollTo: 0},
	{Piscar: 0},
	{Player: 0},
	{Teclado: 0},
	{solido1: 0},
	{PlanoDeFundoEmBlocos4: 0},
	{solido2: 0},
	{decoração: 0},
	{decoração2: 0},
	{moeda: 0},
	{Senóide: 0},
	{boi: 0},
	{vidas: 0},
	{porco: 0},
	{bandeira: 0},
	{Mouse: 0},
	{jogar: 0},
	{fundoDoMenu: 0},
	{galo: 0},
	{Áudio: 0},
	{Tilemap2: 0},
	{decoraFase2: 0},
	{modedaContador: 0},
	{contador: 0},
	{Sprite: 0},
	{Vidas: 0}
];

self.InstanceType = {
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos3: class extends self.ITiledBackgroundInstance {},
	Player: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	solido1: class extends self.ITilemapInstance {},
	PlanoDeFundoEmBlocos4: class extends self.ITiledBackgroundInstance {},
	solido2: class extends self.ITilemapInstance {},
	decoração: class extends self.ITilemapInstance {},
	decoração2: class extends self.ITilemapInstance {},
	moeda: class extends self.ISpriteInstance {},
	boi: class extends self.ISpriteInstance {},
	vidas: class extends self.ISpriteInstance {},
	porco: class extends self.ISpriteInstance {},
	bandeira: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	jogar: class extends self.ISpriteInstance {},
	fundoDoMenu: class extends self.ISpriteInstance {},
	galo: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	Tilemap2: class extends self.ITilemapInstance {},
	decoraFase2: class extends self.ITilemapInstance {},
	modedaContador: class extends self.ISpriteInstance {},
	contador: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {}
}